#!/usr/bin/sh

rm ClimbToGrace.jar
mkdir out

javac -cp lib/javax.json-1.1.jar:src/ src/*.java -d out/ &&
cp -r src/resources/ out/ &&
cd out/ &&
unzip -uo ../lib/javax.json-1.1.jar &&
cd .. &&
jar cvfm ClimbToGrace.jar MANIFEST.MF -C out/ .

rm -r out/
